# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OpenInvite' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OpenInvite

pod 'Firebase'
pod 'Firebase/Firestore'
pod 'PINCache'
pod 'SnapSDK'
pod 'Material'
pod 'SDWebImage'


  target 'OpenInviteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OpenInviteUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
